### ISSUE TITLE
syntax error on macos

### ISSUE THREAD

**Issue by petfik** [yurytch/mc.ext_to_mc.ext.ini#1]
Hi,

I'm getting the following:
```
cat mc.ext | awk -f do.awk > mc.ext.iniNEW
awk: syntax error at source line 13 source file do.awk
 context is
	atch( $0 , /^([^#]*)(regex|type|shell|include|directory)\/(.*)$/ >>>  , <<<  aa ); # !!! might need to check the return
awk: illegal statement at source line 13 source file do.awk
awk: illegal statement at source line 13 source file do.awk
```

**Comment by yurytch** [comment]
I'm not at all sure how this would function on MacOS. I used quite a lot of GNU-awk-isms.
And how come the match statement is at line 13, as it should be at line 16?

**Comment by yurytch** [comment]
Just trying to guess from your diagnostics, might be MacOS awk won't accept the 3rd parameter OR maybe this error is induced by slash-ed syntax for regex constant.

Would you try substituting the quoted line for 
`match( $0 , "^([^#]*)(regex|type|shell|include|directory)\/(.*)$" , aa );`
and trying again?

**Comment by petrfousek** [comment]
I changed the line as you suggested but the output was the same. The line number 13 looks indeed suspicious, something is off here.

But never mind, I just ran your script on linux and it finished fine so I am happy. 

Thanks for your support, yurytch. I think we can close the issue with a note that the script is supposed to be run with a GNU awk.

**Comment by yurytch** [comment]
I have no access to MacOS, so let's do it this way.
