### ISSUE TITLE
syntax error on debian 12.5

### ISSUE THREAD

**Issue by numpa** [yurytch/mc.ext_to_mc.ext.ini#3]
Hi,
I'm getting the following on debian 12.5:

awk: do.awk: line 16: syntax error at or near ,

**Comment by yurytch** [comment]
What's your `gawk --version` output?
EDIT: nevermind, it's 5.2.1? Your issue looks like slash-delimited regexes stop working somehow. Could you try changing outermost slashes to doublequotes in the line 16 and report the result? So that line 16 would look like this:
```
match( $0 , "^([^#]*)(regex|type|shell|include|directory)\/(.*)$" , aa );
```

**Comment by numpa** [comment]
It works! Though it gives this warning:

awk: do.awk:16: warning: escape sequence `\/' treated as plain `/'

> What's your gawk --version output?
> EDIT: nevermind, it's 5.2.1?

Yes, it is.

**Comment by yurytch** [comment]
Glad to hear it. The fresh code should produce no warnings, either. Closing.
